version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: mi_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mi_red

volumes:
  postgres_data:

networks:
  mi_red:
